server:
  port: 8082
spring:
  application:
    name: CUSTOMER-SERVICE
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer-db
eureka:
  instance:
    prefer-ip-address: true
